version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print to output.txt"
          command: echo "Hello World!!!" > output.txt

      - persist_to_workspace:
          root: ~/     # relative path to our working directory must be the same when attaching at.
          paths:      # file globs which will be persisted to the workspace
            - output.txt

  print_output_file:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: print from output file
          command: cat ~/output.txt


workflows:
  share-print-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
